jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
      MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

    strategy:
      matrix:
        CI:
          TESTS: ci
        ITS-MIN:
          TESTS: it
          SQ_VERSION: 7.6
        ITS-LATEST:
          TESTS: it
          SQ_VERSION: LATEST_RELEASE
        ITS-NEXT:
          TESTS: it
          SQ_VERSION: DEV

    steps:
      - task: Cache@2
        inputs:
          key: 'maven | "$(Agent.OS)" | "$(TESTS)" | "$(SQ_VERSION)" | azure-pipelines.yaml, **/pom.xml, !its/sources/**'
          path: $(MAVEN_CACHE_FOLDER)
        displayName: Cache Maven local repo

      - script: |
          ./ci.sh
        displayName: 'Build with Maven'
        env:
          DEPLOY_TOKEN: $(DEPLOY_TOKEN)
          DEPLOY_USERNAME: $(DEPLOY_USERNAME)


  - job: Windows
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    pool:
      vmImage: 'windows-latest'

    variables:
      MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)\.cache\.m2\repository
      SONAR_USER_HOME: $(Pipeline.Workspace)\.cache\.sonar
      MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

    steps:
      - task: Cache@2
        inputs:
          key: 'maven | "$(Agent.OS)" | azure-pipelines.yaml, **/pom.xml, !its/sources/**'
          path: $(Pipeline.Workspace)\.cache
        
      - task: SonarQubePrepare@4
        inputs:
          SonarQube: 'SonarQube'
          scannerMode: 'Other' 

      - task: Maven@3
        inputs:
          goals: 'org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report org.jacoco:jacoco-maven-plugin:report-aggregate'
          options: '-Dsonar.branch.name='
          jdkVersionOption: 1.11
          sonarQubeRunAnalysis: true
          mavenOptions: '$(MAVEN_OPTS)'

      - task: PublishCodeCoverageResults@1
        inputs:
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/report-aggregate/target/site/jacoco-aggregate/jacoco.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/report-aggregate/target/site/jacoco-aggregate'
